In [2]:
import pandas as pd
from numpy import array
from numpy import mean
from numpy import cov

from numpy.linalg import eig


In [3]:
#define a matrix

mat = array([[2.5,2.4],
           [0.5,0.7],
           [2.2,2.9],
           [1.9,2.2],
           [3.1,3.0],
           [2.3,2.7],
           [2,1.6],
           [1,1.1],
           [1.5,1.6],
           [1.1,0.9]])

In [4]:
mat

array([[2.5, 2.4],
       [0.5, 0.7],
       [2.2, 2.9],
       [1.9, 2.2],
       [3.1, 3. ],
       [2.3, 2.7],
       [2. , 1.6],
       [1. , 1.1],
       [1.5, 1.6],
       [1.1, 0.9]])

In [7]:
#mean of matrix
M = mean(mat.T, axis=1)
M

array([1.81, 1.91])

In [18]:
#centered matrix
centered_mat = mat - M
centered_mat

array([[ 0.69,  0.49],
       [-1.31, -1.21],
       [ 0.39,  0.99],
       [ 0.09,  0.29],
       [ 1.29,  1.09],
       [ 0.49,  0.79],
       [ 0.19, -0.31],
       [-0.81, -0.81],
       [-0.31, -0.31],
       [-0.71, -1.01]])

In [19]:
#covariance matrix of centered matrix
cov_mat = cov(centered_mat.T)
cov_mat

array([[0.61655556, 0.61544444],
       [0.61544444, 0.71655556]])

In [20]:
#eigen decomposition of covairance matrix
values, vectors = eig(cov_mat)

In [21]:
vectors

array([[-0.73517866, -0.6778734 ],
       [ 0.6778734 , -0.73517866]])

In [22]:
values

array([0.0490834 , 1.28402771])

In [23]:
#projecting data
proj = vectors.T.dot(centered_mat.T)

In [24]:
proj.T

array([[-0.17511531, -0.82797019],
       [ 0.14285723,  1.77758033],
       [ 0.38437499, -0.99219749],
       [ 0.13041721, -0.27421042],
       [-0.20949846, -1.67580142],
       [ 0.17528244, -0.9129491 ],
       [-0.3498247 ,  0.09910944],
       [ 0.04641726,  1.14457216],
       [ 0.01776463,  0.43804614],
       [-0.16267529,  1.22382056]])

In [25]:
from sklearn.decomposition import PCA


In [27]:
pca = PCA(2)
pca.fit_transform(mat)

array([[-0.82797019, -0.17511531],
       [ 1.77758033,  0.14285723],
       [-0.99219749,  0.38437499],
       [-0.27421042,  0.13041721],
       [-1.67580142, -0.20949846],
       [-0.9129491 ,  0.17528244],
       [ 0.09910944, -0.3498247 ],
       [ 1.14457216,  0.04641726],
       [ 0.43804614,  0.01776463],
       [ 1.22382056, -0.16267529]])

In [28]:
print(pca.components_)

[[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]


In [29]:
print(pca.explained_variance_)

[1.28402771 0.0490834 ]


In [31]:
transformed_data = pca.transform(mat)
transformed_data

array([[-0.82797019, -0.17511531],
       [ 1.77758033,  0.14285723],
       [-0.99219749,  0.38437499],
       [-0.27421042,  0.13041721],
       [-1.67580142, -0.20949846],
       [-0.9129491 ,  0.17528244],
       [ 0.09910944, -0.3498247 ],
       [ 1.14457216,  0.04641726],
       [ 0.43804614,  0.01776463],
       [ 1.22382056, -0.16267529]])